#!/bin/bash
    shopt -s extglob
    start=$(date +%s.%N)
    version=1.00;

    prsopt1="1"; keyword1="option1"; task1="task_1";
    prsopt2="2"; keyword2="option2"; task2="task_2";
    prsoptn="n"; keyword3="optionn"; taskn="task_n";

    ## Configuration Options:    

## Preamble:
    ## Install Dependencies
        dpkg -s fping > /dev/null 2>&1 || { echo "Installing package fping, please verify user passphrase:"; sudo apt-get update && sudo apt-get install fping; };
        dpkg -s terminator > /dev/null 2>&1 || { echo "Installing package terminator, please verify user passphrase:"; sudo apt-get install terminator; };

    ## Define Variables
        b='tput setaf 0'; r='tput setaf 1'; g='tput setaf 2';   # Bash tput colors - black | red | green
        y='tput setaf 3'; u='tput setaf 4'; m='tput setaf 5';   # Bash tput colors - yellow | blue | magenta
        c='tput setaf 6'; w='tput setaf 7'; s='tput sgr0';      # Bash tput colors - cyan | white | default
        d='tput bold'; chnm='^[0-9]+$';                         # Bash tput input - bold | check_for_number
        clrstd=256; clrwrn=214; clrerr=196;                             # prtclr color input - standard | warning | error
        clrnom=113; clrqit=69; user=""    								# prtclr color input - nominal | quiet | user_email

    ## Define Functions
        boottime () {   # Time since script start
            current=$(date +%s.%N);
            out="$(echo "$current - $start" | bc | awk '{printf "%.3f", $0}')"
            echo $out;
        }

        ckconnect () {  # Check connection status to IPt
            fping -t $2 -c 1 $1 > /dev/null 2>&1
            echo $?
        }

        prtclr () {  # Print-to-terminal w/ various arguments                     # Input 1 = Text to print
                                                                                  # Input 2 = Text color        $t<n,e,w,s>color
            timestamp=$(boottime);                                                # Input 3 = Message Type      e for error; w for warning; q for quiet; n for nominal; empty for none
                                                                                  # Input 4 = Bold              Set input "d"
            [[ $4 = "d" ]] && tput bold;                                          # Input 5 = No extra line     Set input "n" for no extra space
            [[ $5 = "n" ]] && prtout="printf" || prtout="echo";
                case $3 in
                    e)  # Error message
                        outstatus=$($prtout "ERROR     [$timestamp]   $outclr");
                    ;;
                    w)  # Warning message
                        outstatus=$($prtout "WARNING   [$timestamp]   $outclr");
                    ;;
                    q)  # Quiet message
                        outstatus=$($prtout "QUIET     [$timestamp]   $outclr");
                    ;;
                    n)  # Status message
                        outstatus=$($prtout "STATUS    [$timestamp]   $outclr");
                    ;;
                    *)  # All other
                        outstatus=$($prtout "$outclr");
                    ;;
                esac

                if [[ $2 -lt 256 ]] && [[ $2 -ge 0 ]]; then     # Check for color input
                    local outclr=$(echo -e -n "\e[38;5;${2}m${outstatus}${1}");
                else
                    tput sgr0;                                  # No color input
                    local outclr=$(echo -e -n "${outstatus}${1}");
                fi

            $prtout "$outclr";                                  # $prtout is the print-method (printf or echo). $outclr is the concatenated message with color applied
            tput sgr0;                                          # Set the terminal output back to default
        }

        ntbash () { # New terminal bash command                                                         # Input 1 = "<Command to run>"
        	terminator -T $title --new-tab -x > /dev/null 2>&1 "sh -c '$1; sleep 20000; exit;';";
            #gnome-terminal --tab -t $2 -e > /dev/null 2>&1 'sh -c "$1; sleep 20000; exit;"';            # Input 2 = "<terminal_title>"
        }

        countdown () {  # Pause script and terminal-output countdown
            [[ $2 = "down" ]] && inmt="--" || inmt="++";    # Input 2 = "down", then increment down. Otherwise, count up
            for (( i = $1; i > -1 && i < 20; i$inmt )); do
                echo -e -n "\r$i "; echo -e -n "seconds";
                [[ ! $i = 0 ]] && sleep 1;
            done
        }

        dyncheck () {   # Dynamically check for remote host                                             # Input 1 = Timeout [s]
            [[ ! -z ${4+x} ]] && vcl=$4;                                                                # Input 2 = Interval between pings [s]
            run="1"; timeout=$(($1)); wait=$2; quiet=$3; t="0";                                         # Input 3 = Ouput quiet? 0 = False, 1 = True (do not print)
                while [[ $run = "1" ]] && [[ $t -lt $timeout ]]; do                                     # Input 4 = Remote host ID (usually use $vcl or SSH IP-Addresses)
                    e2e=$(ckconnect "$vcl" "100");
                    [[ $t -ge "60" ]] && wait="10";
                   if [[ ! $e2e = "0" ]]; then
                       t=$((t+$wait)); prtclr "Waiting for $vcl - Timeout ${t}/${timeout} Seconds..." "$clrqit" "x" "x" "q"; sleep $wait;
                   else
                       run="0"; [[ $quiet = "0" ]] && prtclr "Host Detected" "$clrnom" "x" "x" "n";
                   fi
                done
            [[ $run = "1" ]] && nodetect=1 || nodetect=0;
        }

        makeconfig () {
            if [ ! -f $rootfolder/config ]; then
                touch $rootfolder/config;
                
                prtclr "Customize user configuration? (y/n)" "256";
                read customize; ! [[ $customize = "y" || $customize = "n" ]] && { prtclr "Warning: Spurious input, applying default settings" "220"; customize="n"; }
                
                if ! [[ $customize = "y" ]]; then                                                   # Default configuration settings
                    
                    echo "Version: $version" > $rootfolder/config;
                    echo "User Configuration File:" >> $rootfolder/config;
                    echo "standout_color: 256" >> $rootfolder/config;
                    echo "warn_color: 220" >> $rootfolder/config;
                    echo "error_color: 196" >> $rootfolder/config;
                    echo "nominal_color: 114" >> $rootfolder/config;
                    echo "quiet_color: 37" >> $rootfolder/config;
                    prtclr "Enter user email: " "256";
                    read user; echo "user: $user" >> $rootfolder/config;
                    prtclr "Default Text Colors:" "256"
                    prtclr "Status Report:" "256"; prtclr "Warning: Oil Temp Hot" "220";
                    prtclr "Error: Hull Breach Detected" "196"; prtclr "All Systems Nominal" "47";
                    countdown "3" "down"; echo
                    
                else
                    
                    echo "Please configure custom user options: "; echo;
                    
                    verify="n";
                    while [[ $verify = "n" ]]; do
                        echo "Version: $version" > $rootfolder/config;
                        echo "User Configuration File:" >> $rootfolder/config;
                        
                        ## Text Color ##
                        printable_colours=256
                        
                        echo
                        prtblk 16 231 6 6 3 # The bulk of colours are between 16 and 231 inclusive
                        prtblk 232 255 12 2 1 # Not 50, but 24 Shades of Grey
                        prtclr "256" "256";
                        echo;
                        
                        prtclr "Prompting text color? (0-255)" "256";
                        read clrstd && echo "standout_color: $clrstd" >> $rootfolder/config;
                        
                        prtclr "Warning text color? (0-255)" "$clrstd"
                        read clrwrn && echo "warn_color: $clrwrn" >> $rootfolder/config;
                        
                        prtclr "Error text color? (0-255)" "$clrstd"
                        read clrerr && echo "error_color: $clrerr" >> $rootfolder/config;
                        
                        prtclr "Nominal text color? (0-255)" "$clrstd"
                        read clrnom && echo "nominal_color: $clrnom" >> $rootfolder/config;
                        
                        prtclr "Quiet text color? (0-255)" "$clrstd"
                        read clrqit && echo "quiet_color: $clrqit" >> $rootfolder/config;
                        
                        echo
                        prtclr "Status Report:" "$clrstd"; prtclr "Warning: Oil Temp Hot" "$clrwrn";
                        prtclr "Error: Hull Breach Detected" "$clrerr"; prtclr "All Systems Nominal" "$clrnom"; prtclr "Quiet: They'll Hear You" "$clrqit";
                        echo
                        echo "Text Colors Okay? (y/n): "
                        read verify; ! [[ $verify = "y" || $verify = "n" ]] && { prtclr "Warning: spurious config input" "$clrwrn"; verify="n"; }; echo "verify: $verify" >> $rootfolder/config;                        
                    
                    done
                    
                    prtclr "Option 1 ()" "$clrstd"
                    read option1; ! [[ $option1 = "1" || $thold = "2" ]] && { prtclr "Warning: spurious config input. Defaulting to 2" "$clrwrn"; thold="2"; }; echo "option_1: $option1" >> $rootfolder/config;
                    
                    prtclr "User configuration saved in $rootfolder..." "$clrnom";
                    sleep 1;
                fi   
            else  
                checksum=$(sed -n 's/Version: //p' $rootfolder/config);

                ! [[ $checksum = $version ]] && ( rm $rootfolder/config; echo "Updating user config file..."; sleep 2; makeconfig );
                
                clrstd=$(sed -n 's/standout_color: //p' $rootfolder/config);
                clrwrn=$(sed -n 's/warn_color: //p' $rootfolder/config);
                clrerr=$(sed -n 's/error_color: //p' $rootfolder/config);
                clrnom=$(sed -n 's/nominal_color: //p' $rootfolder/config);
                clrqit=$(sed -n 's/quiet_color: //p' $rootfolder/config);
            fi 
        }

## Pre-execution:

    ## Parse input for tasks:
        while [[ $# > 0 ]]; do
            case "$1" in
                
                -$prsopt1|--$keyword1)
                    option+=" $task1"
                    v1+="$2"
                    shift
                    { texe+="1"; optname+=' task1'; };
                ;;

                -$prsopt2|--$keyword2)
                    option+=" $task2"
                    v2+="$2"
                    shift
                    { texe+="1"; optname+=' task2'; };
                ;;

                --config)
                    rm $rootfolder/config;
                    makeconfig
                    netID+="0"
                    skipscp="1"
                    exit
                ;;
                
                -i)
                    netID+="$2"
                    shift
                ;;
                
                -h|--help|*)
                    echo $1;
                    cat $rootfolder/help;
                    echo
                    exit
                ;;
            esac
            shift   # While there are still input arguments to parse, do:
            
        done

## Functional Script:
    ## Available functions: boottime(), ckconnect(), prtclr(), ntssh(), ctssh(), ntbash(), countdown(), dyncheck()
    
rootFolder="$HOME/Engineering/Python/VSCode/sensorData";
sensors=(imu dht11);
scripts=(${rootFolder}/scripts/mpuData.py ${rootFolder}/scripts/dht11Data.py);
echo ${scripts[@]}; sleep 1;

[[ $(pwd) == $rootFolder ]] || cd "${rootFolder}";
ls -la | grep -i logs; logFolder=$(echo $?);
[[ ${logFolder} == 0 ]] || mkdir -p logs;

for i in "${!sensors[@]}"; do
    LOG=logs/"${sensors[$i]}"_$(date +%Y%m%d_%H%M%S).csv;
    echo "Logging to $LOG";
    ls -la logs/;

    sensor="${sensors[$i]}";
    script="${scripts[$i]}";

    mpremote connect /dev/ttyACM0 run "$script" | tee -a "$LOG";
done